
library(fpp2)
Rate <- read.csv(file.choose())
attach(Rate)
head(Rate,n=12)
#QUARTERLY
Ratets<- ts(Rate[,"Value"], start=c(2000,1),frequency =4)
plot(Ratets, main="Guatemalan Exchange Rate(Quarterly)", ylab="Value", xlab="Time", col=6)
ggseasonplot(Ratets,polar=T)
ArimaMod <- auto.arima(Ratets)
summary(ArimaMod)
checkresiduals(ArimaMod)
forecast(ArimaMod,h=20)
plot(forecast(ArimaMod,h=20))
EtsMod <- ets(Ratets)
summary(EtsMod)
checkresiduals(EtsMod)
forecast(EtsMod)
plot(forecast(EtsMod))
rwfMod <-rwf(Ratets,drift=T)
plot(rwfMod)
summary(rwfMod)
checkresiduals(rwfMod)
#YEARLY
yearR <- read.csv(file.choose())
yearR
attach(yearR)
yearRts <- ts(yearR[,"Value"], start=c(2000,1),frequency = 1)
plot(yearRts, main="Guatemalan Exchange Rate(Yearly)", ylab="Value",xlab="Time",col=6)
ArimaMod2 <- auto.arima(yearRts)
summary(ArimaMod2)
checkresiduals(ArimaMod2)
forecast(ArimaMod2)
plot(forecast(ArimaMod2))
EtsMod2 <- ets(yearRts)
summary(EtsMod2)
checkresiduals(EtsMod2)
forecast(EtsMod2)
plot(forecast(EtsMod2))
rwfMod2 <-rwf(yearRts,drift=T)
plot(rwfMod2)
summary(rwfMod2)
checkresiduals(rwfMod2)
forecast(rwfMod2)
